INFO:root:Trying to read old json data
INFO:root:Success
INFO:root:Trying to add new data
INFO:root:Success
INFO:werkzeug:127.0.0.1 - - [16/Aug/2021 18:35:48] "GET / HTTP/1.1" 200 -
INFO:root:Trying to read old json data
ERROR:app:Exception on / [GET]
Traceback (most recent call last):
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kirill/PycharmProjects/flaskProject/app.py", line 55, in get_my_ip
    save_to_json(need_info)
  File "/home/kirill/PycharmProjects/flaskProject/app.py", line 15, in save_to_json
    old_json = json.load(json_file)
  File "/usr/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:werkzeug:127.0.0.1 - - [16/Aug/2021 18:36:15] "[35m[1mGET / HTTP/1.1[0m" 500 -
INFO:root:Trying to read old json data
ERROR:app:Exception on / [GET]
Traceback (most recent call last):
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kirill/PycharmProjects/flaskProject/app.py", line 55, in get_my_ip
    save_to_json(need_info)
  File "/home/kirill/PycharmProjects/flaskProject/app.py", line 15, in save_to_json
    old_json = json.load(json_file)
  File "/usr/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:werkzeug:127.0.0.1 - - [16/Aug/2021 18:36:19] "[35m[1mGET / HTTP/1.1[0m" 500 -
INFO:root:Trying to read old json data
ERROR:app:Exception on / [GET]
Traceback (most recent call last):
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kirill/PycharmProjects/flaskProject/app.py", line 55, in get_my_ip
    save_to_json(need_info)
  File "/home/kirill/PycharmProjects/flaskProject/app.py", line 15, in save_to_json
    old_json = json.load(json_file)
  File "/usr/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:werkzeug:127.0.0.1 - - [16/Aug/2021 18:36:27] "[35m[1mGET / HTTP/1.1[0m" 500 -
INFO:root:Trying to read old json data
ERROR:app:Exception on / [GET]
Traceback (most recent call last):
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kirill/PycharmProjects/flaskProject/app.py", line 55, in get_my_ip
    save_to_json(need_info)
  File "/home/kirill/PycharmProjects/flaskProject/app.py", line 15, in save_to_json
    old_json = json.load(json_file)
  File "/usr/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:werkzeug:127.0.0.1 - - [16/Aug/2021 18:37:14] "[35m[1mGET / HTTP/1.1[0m" 500 -
INFO:root:Trying to read old json data
ERROR:app:Exception on / [GET]
Traceback (most recent call last):
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kirill/PycharmProjects/flaskProject/app.py", line 55, in get_my_ip
    save_to_json(need_info)
  File "/home/kirill/PycharmProjects/flaskProject/app.py", line 15, in save_to_json
    old_json = json.load(json_file)
  File "/usr/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:werkzeug:127.0.0.1 - - [16/Aug/2021 18:37:44] "[35m[1mGET / HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [16/Aug/2021 18:37:44] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO:root:Trying to read old json data
ERROR:app:Exception on / [GET]
Traceback (most recent call last):
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kirill/PycharmProjects/flaskProject/app.py", line 55, in get_my_ip
    save_to_json(need_info)
  File "/home/kirill/PycharmProjects/flaskProject/app.py", line 15, in save_to_json
    old_json = json.load(json_file)
  File "/usr/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:werkzeug:127.0.0.1 - - [16/Aug/2021 18:37:50] "[35m[1mGET / HTTP/1.1[0m" 500 -
INFO:root:Trying to read old json data
ERROR:app:Exception on / [GET]
Traceback (most recent call last):
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kirill/PycharmProjects/flaskProject/app.py", line 56, in get_my_ip
    save_to_json(need_info)
  File "/home/kirill/PycharmProjects/flaskProject/app.py", line 15, in save_to_json
    old_json = json.load(json_file)
  File "/usr/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:werkzeug:127.0.0.1 - - [16/Aug/2021 18:38:23] "[35m[1mGET / HTTP/1.1[0m" 500 -
INFO:root:Trying to read old json data
ERROR:app:Exception on / [GET]
Traceback (most recent call last):
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kirill/PycharmProjects/flaskProject/app.py", line 57, in get_my_ip
    save_to_json(need_info)
  File "/home/kirill/PycharmProjects/flaskProject/app.py", line 15, in save_to_json
    old_json = json.load(json_file)
  File "/usr/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:werkzeug:127.0.0.1 - - [16/Aug/2021 18:39:06] "[35m[1mGET / HTTP/1.1[0m" 500 -
INFO:root:Trying to read old json data
ERROR:app:Exception on / [GET]
Traceback (most recent call last):
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kirill/PycharmProjects/flaskProject/app.py", line 57, in get_my_ip
    save_to_json(need_info)
  File "/home/kirill/PycharmProjects/flaskProject/app.py", line 15, in save_to_json
    old_json = json.load(json_file)
  File "/usr/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:werkzeug:127.0.0.1 - - [16/Aug/2021 18:39:22] "[35m[1mGET / HTTP/1.1[0m" 500 -
INFO:root:Trying to read old json data
ERROR:app:Exception on / [GET]
Traceback (most recent call last):
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kirill/PycharmProjects/flaskProject/app.py", line 57, in get_my_ip
    save_to_json(need_info)
  File "/home/kirill/PycharmProjects/flaskProject/app.py", line 15, in save_to_json
    old_json = json.load(json_file)
  File "/usr/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:werkzeug:127.0.0.1 - - [16/Aug/2021 18:39:31] "[35m[1mGET / HTTP/1.1[0m" 500 -
INFO:root:Trying to read old json data
ERROR:app:Exception on / [GET]
Traceback (most recent call last):
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kirill/PycharmProjects/flaskProject/app.py", line 59, in get_my_ip
    save_to_json(need_info)
  File "/home/kirill/PycharmProjects/flaskProject/app.py", line 15, in save_to_json
    old_json = json.load(json_file)
  File "/usr/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:werkzeug:127.0.0.1 - - [16/Aug/2021 18:39:44] "[35m[1mGET / HTTP/1.1[0m" 500 -
INFO:root:Trying to read old json data
ERROR:app:Exception on / [GET]
Traceback (most recent call last):
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kirill/PycharmProjects/flaskProject/app.py", line 60, in get_my_ip
    save_to_json(need_info)
  File "/home/kirill/PycharmProjects/flaskProject/app.py", line 15, in save_to_json
    old_json = json.load(json_file)
  File "/usr/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:werkzeug:127.0.0.1 - - [16/Aug/2021 18:42:28] "[35m[1mGET / HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:root:Trying to read old json data
ERROR:app:Exception on / [GET]
Traceback (most recent call last):
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kirill/PycharmProjects/flaskProject/app.py", line 60, in get_my_ip
    save_to_json(need_info)
  File "/home/kirill/PycharmProjects/flaskProject/app.py", line 15, in save_to_json
    old_json = json.load(json_file)
  File "/usr/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:werkzeug:127.0.0.1 - - [16/Aug/2021 18:42:46] "[35m[1mGET / HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
ERROR:app:Exception on / [GET]
Traceback (most recent call last):
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kirill/PycharmProjects/flaskProject/app.py", line 60, in get_my_ip
    save_to_json(need_info)
  File "/home/kirill/PycharmProjects/flaskProject/app.py", line 15, in save_to_json
    old_json = json.load(json_file)
  File "/usr/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:werkzeug:127.0.0.1 - - [16/Aug/2021 18:43:07] "[35m[1mGET / HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
ERROR:app:Exception on / [GET]
Traceback (most recent call last):
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kirill/PycharmProjects/flaskProject/app.py", line 62, in get_my_ip
    save_to_json(need_info)
  File "/home/kirill/PycharmProjects/flaskProject/app.py", line 15, in save_to_json
    old_json = json.load(json_file)
  File "/usr/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:werkzeug:127.0.0.1 - - [16/Aug/2021 18:43:22] "[35m[1mGET / HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
ERROR:app:Exception on / [GET]
Traceback (most recent call last):
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kirill/PycharmProjects/flaskProject/app.py", line 63, in get_my_ip
    save_to_json(need_info)
  File "/home/kirill/PycharmProjects/flaskProject/app.py", line 16, in save_to_json
    json_file = open("date.json", mode="r", encoding="Latin-1")
  File "/home/kirill/PycharmProjects/flaskProject/app.py", line 16, in save_to_json
    json_file = open("date.json", mode="r", encoding="Latin-1")
  File "/usr/lib/python3.7/bdb.py", line 88, in trace_dispatch
    return self.dispatch_line(frame)
  File "/usr/lib/python3.7/bdb.py", line 113, in dispatch_line
    if self.quitting: raise BdbQuit
bdb.BdbQuit
INFO:werkzeug:127.0.0.1 - - [16/Aug/2021 18:45:16] "[35m[1mGET / HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [16/Aug/2021 18:45:28] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Aug/2021 18:45:40] "GET / HTTP/1.1" 200 -
ERROR:app:Exception on / [GET]
Traceback (most recent call last):
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kirill/PycharmProjects/flaskProject/app.py", line 63, in get_my_ip
    save_to_json(need_info)
  File "/home/kirill/PycharmProjects/flaskProject/app.py", line 23, in save_to_json
    old_json.update(date)
  File "/usr/lib/python3.7/json/__init__.py", line 179, in dump
    for chunk in iterable:
  File "/usr/lib/python3.7/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.7/json/encoder.py", line 340, in _iterencode_dict
    raise ValueError("Circular reference detected")
ValueError: Circular reference detected
INFO:werkzeug:127.0.0.1 - - [16/Aug/2021 18:50:15] "[35m[1mGET / HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
ERROR:app:Exception on / [GET]
Traceback (most recent call last):
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kirill/PycharmProjects/flaskProject/app.py", line 63, in get_my_ip
    save_to_json(need_info)
  File "/home/kirill/PycharmProjects/flaskProject/app.py", line 23, in save_to_json
    old_json
  File "/home/kirill/PycharmProjects/flaskProject/app.py", line 23, in save_to_json
    old_json
  File "/usr/lib/python3.7/bdb.py", line 88, in trace_dispatch
    return self.dispatch_line(frame)
  File "/usr/lib/python3.7/bdb.py", line 113, in dispatch_line
    if self.quitting: raise BdbQuit
bdb.BdbQuit
INFO:werkzeug:127.0.0.1 - - [16/Aug/2021 18:50:55] "[35m[1mGET / HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
ERROR:app:Exception on / [GET]
Traceback (most recent call last):
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kirill/PycharmProjects/flaskProject/app.py", line 65, in get_my_ip
    save_to_json(need_info)
  File "/home/kirill/PycharmProjects/flaskProject/app.py", line 26, in save_to_json
    json_file = open("date.json", mode="w", encoding="Latin-1")
  File "/home/kirill/PycharmProjects/flaskProject/app.py", line 26, in save_to_json
    json_file = open("date.json", mode="w", encoding="Latin-1")
  File "/usr/lib/python3.7/bdb.py", line 88, in trace_dispatch
    return self.dispatch_line(frame)
  File "/usr/lib/python3.7/bdb.py", line 113, in dispatch_line
    if self.quitting: raise BdbQuit
bdb.BdbQuit
INFO:werkzeug:127.0.0.1 - - [16/Aug/2021 18:52:38] "[35m[1mGET / HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [16/Aug/2021 18:53:01] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Aug/2021 18:59:34] "GET / HTTP/1.1" 200 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
ERROR:app:Exception on / [GET]
Traceback (most recent call last):
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kirill/PycharmProjects/flaskProject/app.py", line 61, in get_my_ip
    need_info["user"].update(location)
KeyError: 'user'
INFO:werkzeug:127.0.0.1 - - [16/Aug/2021 18:59:39] "[35m[1mGET / HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
ERROR:app:Exception on / [GET]
Traceback (most recent call last):
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kirill/PycharmProjects/flaskProject/app.py", line 61, in get_my_ip
    location = get_location("85.238.119.89")
KeyError: 'user'
INFO:werkzeug:127.0.0.1 - - [16/Aug/2021 19:00:14] "[35m[1mGET / HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
ERROR:app:Exception on / [GET]
Traceback (most recent call last):
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kirill/PycharmProjects/flaskProject/app.py", line 61, in get_my_ip
    location = get_location("85.238.119.89")
KeyError: 'user'
INFO:werkzeug:127.0.0.1 - - [16/Aug/2021 19:00:31] "[35m[1mGET / HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
ERROR:app:Exception on / [GET]
Traceback (most recent call last):
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kirill/PycharmProjects/flaskProject/app.py", line 63, in get_my_ip
    location = get_location("85.238.119.89")
KeyError: 'user'
INFO:werkzeug:127.0.0.1 - - [16/Aug/2021 19:01:23] "[35m[1mGET / HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [16/Aug/2021 19:04:21] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Aug/2021 19:06:05] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Aug/2021 19:06:29] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Aug/2021 19:06:45] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Aug/2021 19:07:39] "GET / HTTP/1.1" 200 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [16/Aug/2021 19:08:12] "GET / HTTP/1.1" 200 -
ERROR:app:Exception on / [GET]
Traceback (most recent call last):
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kirill/PycharmProjects/flaskProject/app.py", line 62, in get_my_ip
    location = get_location("78.26.242.56")
  File "/home/kirill/PycharmProjects/flaskProject/app.py", line 36, in get_location
    response = requests.get(location_url)
  File "/home/kirill/PycharmProjects/flaskProject/app.py", line 36, in get_location
    response = requests.get(location_url)
  File "/usr/lib/python3.7/bdb.py", line 88, in trace_dispatch
    return self.dispatch_line(frame)
  File "/usr/lib/python3.7/bdb.py", line 113, in dispatch_line
    if self.quitting: raise BdbQuit
bdb.BdbQuit
INFO:werkzeug:127.0.0.1 - - [16/Aug/2021 19:09:35] "[35m[1mGET / HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
ERROR:app:Exception on / [GET]
Traceback (most recent call last):
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kirill/PycharmProjects/flaskProject/app.py", line 64, in get_my_ip
    need_info[all_data.get("REMOTE_ADDR")].update(location)
KeyError: '127.0.0.1'
INFO:werkzeug:127.0.0.1 - - [16/Aug/2021 19:09:42] "[35m[1mGET / HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
ERROR:app:Exception on / [GET]
Traceback (most recent call last):
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kirill/PycharmProjects/flaskProject/app.py", line 64, in get_my_ip
    need_info[all_data.get("REMOTE_ADDR")].update(location)
KeyError: '127.0.0.1'
INFO:werkzeug:127.0.0.1 - - [16/Aug/2021 19:09:54] "[35m[1mGET / HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [16/Aug/2021 19:10:32] "GET / HTTP/1.1" 200 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [16/Aug/2021 19:12:33] "GET / HTTP/1.1" 200 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
ERROR:app:Exception on / [GET]
Traceback (most recent call last):
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kirill/PycharmProjects/flaskProject/app.py", line 59, in get_my_ip
  File "/home/kirill/PycharmProjects/flaskProject/app.py", line 59, in get_my_ip
  File "/usr/lib/python3.7/bdb.py", line 88, in trace_dispatch
    return self.dispatch_line(frame)
  File "/usr/lib/python3.7/bdb.py", line 113, in dispatch_line
    if self.quitting: raise BdbQuit
bdb.BdbQuit
INFO:werkzeug:127.0.0.1 - - [16/Aug/2021 19:19:53] "[35m[1mGET / HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
ERROR:app:Exception on / [GET]
Traceback (most recent call last):
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kirill/PycharmProjects/flaskProject/app.py", line 52, in get_my_ip
    date = datetime.now().strftime("%Y-%d-%m %H:%M:%S")
AttributeError: module 'datetime' has no attribute 'now'
INFO:werkzeug:127.0.0.1 - - [16/Aug/2021 19:19:59] "[35m[1mGET / HTTP/1.1[0m" 500 -
ERROR:app:Exception on / [GET]
Traceback (most recent call last):
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kirill/PycharmProjects/flaskProject/app.py", line 52, in get_my_ip
    date = datetime.now().strftime("%Y-%d-%m %H:%M:%S")
AttributeError: module 'datetime' has no attribute 'now'
INFO:werkzeug:127.0.0.1 - - [16/Aug/2021 19:20:00] "[35m[1mGET / HTTP/1.1[0m" 500 -
ERROR:app:Exception on / [GET]
Traceback (most recent call last):
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kirill/PycharmProjects/flaskProject/app.py", line 52, in get_my_ip
    date = datetime.now().strftime("%Y-%d-%m %H:%M:%S")
AttributeError: module 'datetime' has no attribute 'now'
INFO:werkzeug:127.0.0.1 - - [16/Aug/2021 19:20:03] "[35m[1mGET / HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
ERROR:app:Exception on / [GET]
Traceback (most recent call last):
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kirill/PycharmProjects/flaskProject/app.py", line 52, in get_my_ip
    date = datetime.now().strftime("%Y-%d-%m %H:%M:%S")
AttributeError: module 'datetime' has no attribute 'now'
INFO:werkzeug:127.0.0.1 - - [16/Aug/2021 19:20:21] "[35m[1mGET / HTTP/1.1[0m" 500 -
ERROR:app:Exception on / [GET]
Traceback (most recent call last):
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kirill/PycharmProjects/flaskProject/app.py", line 52, in get_my_ip
    date = datetime.now().strftime("%Y-%d-%m %H:%M:%S")
AttributeError: module 'datetime' has no attribute 'now'
INFO:werkzeug:127.0.0.1 - - [16/Aug/2021 19:20:21] "[35m[1mGET / HTTP/1.1[0m" 500 -
ERROR:app:Exception on / [GET]
Traceback (most recent call last):
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kirill/PycharmProjects/flaskProject/app.py", line 52, in get_my_ip
    date = datetime.now().strftime("%Y-%d-%m %H:%M:%S")
AttributeError: module 'datetime' has no attribute 'now'
INFO:werkzeug:127.0.0.1 - - [16/Aug/2021 19:20:22] "[35m[1mGET / HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
ERROR:app:Exception on / [GET]
Traceback (most recent call last):
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kirill/PycharmProjects/flaskProject/app.py", line 52, in get_my_ip
    date = datetime.now().strftime("%Y-%d-%m %H:%M:%S")
AttributeError: module 'datetime' has no attribute 'now'
INFO:werkzeug:127.0.0.1 - - [16/Aug/2021 19:20:33] "[35m[1mGET / HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
ERROR:app:Exception on / [GET]
Traceback (most recent call last):
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kirill/PycharmProjects/flaskProject/app.py", line 53, in get_my_ip
    date = datetime.datetime.now().strftime("%Y-%d-%m %H:%M:%S")
  File "/home/kirill/PycharmProjects/flaskProject/app.py", line 53, in get_my_ip
    date = datetime.datetime.now().strftime("%Y-%d-%m %H:%M:%S")
  File "/usr/lib/python3.7/bdb.py", line 88, in trace_dispatch
    return self.dispatch_line(frame)
  File "/usr/lib/python3.7/bdb.py", line 113, in dispatch_line
    if self.quitting: raise BdbQuit
bdb.BdbQuit
INFO:werkzeug:127.0.0.1 - - [16/Aug/2021 19:21:01] "[35m[1mGET / HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:root:Trying to read old json data
INFO:root:Success
INFO:root:Trying to add new data
INFO:root:Success
INFO:werkzeug:127.0.0.1 - - [16/Aug/2021 19:21:22] "GET / HTTP/1.1" 200 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:root:Trying to read old json data
INFO:root:Success
INFO:root:Trying to add new data
INFO:root:Success
INFO:werkzeug:127.0.0.1 - - [16/Aug/2021 19:21:46] "GET / HTTP/1.1" 200 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:root:Trying to read old json data
INFO:root:Success
INFO:root:Trying to add new data
INFO:root:Success
INFO:werkzeug:127.0.0.1 - - [16/Aug/2021 19:23:03] "GET / HTTP/1.1" 200 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:root:Trying to read old json data
INFO:root:Success
INFO:root:Trying to add new data
INFO:root:Success
INFO:werkzeug:127.0.0.1 - - [16/Aug/2021 19:26:11] "GET / HTTP/1.1" 200 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:root:Trying to read old json data
INFO:root:Success
INFO:root:Trying to add new data
INFO:root:Success
INFO:werkzeug:127.0.0.1 - - [16/Aug/2021 19:26:24] "GET / HTTP/1.1" 200 -
INFO:root:Trying to read old json data
INFO:root:Success
INFO:root:Trying to add new data
INFO:root:Success
INFO:werkzeug:127.0.0.1 - - [16/Aug/2021 19:27:55] "GET / HTTP/1.1" 200 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:root:Trying to read old json data
INFO:root:Success
INFO:root:Trying to add new data
INFO:root:Success
INFO:werkzeug:127.0.0.1 - - [16/Aug/2021 19:28:00] "GET / HTTP/1.1" 200 -
INFO:root:Trying to read old json data
INFO:root:Success
INFO:root:Trying to add new data
INFO:root:Success
INFO:werkzeug:127.0.0.1 - - [16/Aug/2021 19:29:17] "GET / HTTP/1.1" 200 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:root:Trying to read old json data
INFO:root:Success
INFO:root:Trying to add new data
INFO:root:Success
INFO:werkzeug:127.0.0.1 - - [16/Aug/2021 19:29:27] "GET / HTTP/1.1" 200 -
INFO:root:Trying to read old json data
INFO:root:Success
INFO:root:Trying to add new data
INFO:root:Success
INFO:werkzeug:127.0.0.1 - - [16/Aug/2021 19:29:40] "GET / HTTP/1.1" 200 -
INFO:root:Trying to read old json data
INFO:root:Success
INFO:root:Trying to add new data
INFO:root:Success
INFO:werkzeug:127.0.0.1 - - [16/Aug/2021 19:29:41] "GET / HTTP/1.1" 200 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:root:Trying to read old json data
INFO:root:Success
INFO:root:Trying to add new data
INFO:root:Success
INFO:werkzeug:127.0.0.1 - - [16/Aug/2021 19:29:43] "GET / HTTP/1.1" 200 -
INFO:root:Trying to read old json data
INFO:root:Success
INFO:root:Trying to add new data
INFO:root:Success
INFO:werkzeug:127.0.0.1 - - [16/Aug/2021 19:29:56] "GET / HTTP/1.1" 200 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:root:Trying to read old json data
INFO:root:Success
INFO:root:Trying to add new data
INFO:root:Success
INFO:werkzeug:127.0.0.1 - - [16/Aug/2021 19:29:59] "GET / HTTP/1.1" 200 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:root:Trying to read old json data
INFO:root:Success
INFO:root:Trying to add new data
INFO:root:Success
INFO:werkzeug:127.0.0.1 - - [16/Aug/2021 19:39:50] "GET / HTTP/1.1" 200 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [16/Aug/2021 19:40:01] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Aug/2021 19:40:08] "GET / HTTP/1.1" 200 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:geocoder.base:Requested https://nominatim.openstreetmap.org/search?q=run&format=jsonv2&addressdetails=1&limit=1
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [16/Aug/2021 19:54:30] "GET / HTTP/1.1" 200 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [16/Aug/2021 20:27:20] "GET / HTTP/1.1" 200 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [16/Aug/2021 20:28:04] "GET / HTTP/1.1" 200 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [16/Aug/2021 20:29:52] "GET / HTTP/1.1" 200 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [16/Aug/2021 21:23:38] "GET / HTTP/1.1" 200 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [16/Aug/2021 21:29:40] "GET / HTTP/1.1" 200 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [16/Aug/2021 21:30:01] "GET / HTTP/1.1" 200 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [16/Aug/2021 21:37:45] "GET / HTTP/1.1" 200 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [16/Aug/2021 21:37:59] "GET / HTTP/1.1" 200 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [17/Aug/2021 10:58:26] "GET / HTTP/1.1" 200 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
ERROR:app:Exception on / [GET]
Traceback (most recent call last):
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kirill/PycharmProjects/flaskProject/app.py", line 59, in get_my_ip
    return render_template('blog/index.html')
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/templating.py", line 148, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/jinja2/environment.py", line 1068, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/jinja2/environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/jinja2/environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/jinja2/loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/templating.py", line 59, in get_source
    return self._get_source_fast(environment, template)
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/templating.py", line 95, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: blog/index.html
INFO:werkzeug:127.0.0.1 - - [17/Aug/2021 10:58:41] "[35m[1mGET / HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [17/Aug/2021 10:58:41] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
ERROR:app:Exception on / [GET]
Traceback (most recent call last):
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kirill/PycharmProjects/flaskProject/app.py", line 59, in get_my_ip
    return render_template('blog/index.html')
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/templating.py", line 148, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/jinja2/environment.py", line 1068, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/jinja2/environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/jinja2/environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/jinja2/loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/templating.py", line 59, in get_source
    return self._get_source_fast(environment, template)
  File "/home/kirill/PycharmProjects/flaskProject/myvenv/lib/python3.7/site-packages/flask/templating.py", line 95, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: blog/index.html
INFO:werkzeug:127.0.0.1 - - [17/Aug/2021 10:58:46] "[35m[1mGET / HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [17/Aug/2021 10:58:54] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [17/Aug/2021 11:01:15] "GET / HTTP/1.1" 200 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [17/Aug/2021 11:01:18] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [17/Aug/2021 11:01:19] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [17/Aug/2021 11:01:32] "GET / HTTP/1.1" 200 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [17/Aug/2021 11:01:35] "GET / HTTP/1.1" 200 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [17/Aug/2021 11:12:45] "GET / HTTP/1.1" 200 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [18/Aug/2021 14:20:42] "GET / HTTP/1.1" 200 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [18/Aug/2021 14:21:10] "GET / HTTP/1.1" 200 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [18/Aug/2021 14:23:01] "GET / HTTP/1.1" 200 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [18/Aug/2021 14:25:32] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Aug/2021 14:25:33] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [18/Aug/2021 14:25:40] "GET /ppzqqtrrl HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Aug/2021 14:25:50] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Aug/2021 14:25:52] "GET /ppzqqtrrl HTTP/1.1" 200 -
